version: "3.8"
services:
  fastapi-app:
    build: .
    ports:
      - "8000:80"  # Maps port 8000 on your local machine to port 80 in the container
    env_file:
      - .env  # This will load environment variables from the .env file
